CREATE OR REPLACE WAREHOUSE DEMO_WH WITH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

CREATE OR REPLACE DATABASE RETAIL_DB;
CREATE OR REPLACE SCHEMA RETAIL_DB.SALES;

USE WAREHOUSE DEMO_WH;
USE DATABASE RETAIL_DB;
USE SCHEMA SALES;
